# Site settings
title: Yicheng.blog()
email: zhangyicheng1234@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lancevalour.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  lancevalour

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Cool Option 1
    link: http://lancevalour.github.io
  option2:
    name: Cool Option 2
    link: http://lancevalour.github.io
  option3:
    name: Cool Option 3
    link: http://lancevalour.github.io

# Build settings
markdown: kramdown
